version: "3.9"

services:
  app:
    build: { context: ., dockerfile: Dockerfile.dev }
    env_file: .env.development
    volumes: [./:/app:cached]
    ports: [8000:8000]
    depends_on: [mongo]
    command: uvicorn app:app --reload --host 0.0.0.0

  mongo:
    image: mongo:5
    restart: unless-stopped
    volumes: [mongodb-data:/data/db]
    ports: [27017:27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

volumes:
  mongodb-data:
