version: "3.9"

services:
  test:
    build: { context: ., dockerfile: Dockerfile.dev }
    env_file: .env.test
    volumes: [./:/app:cached]
    depends_on: [mongo]
    command: pytest .

  mongo:
    image: mongo:5
    restart: unless-stopped
    volumes: [{ type: tmpfs, target: /data/db }]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
