services:
  biblion-code:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.10
    volumes: [./:/app:cached]
    depends_on: [mongo, mailhog]
    init: true
    command: sleep infinity

networks:
  default: { name: "biblion-network" }
