FROM python:3.10

RUN adduser --system python

RUN pip install --no-cache --upgrade pip && pip install --no-cache pipenv

USER python

WORKDIR /app

COPY ./Pipfile ./Pipfile.lock ./

RUN pipenv install --dev --deploy --ignore-pipfile --clear

COPY ./ ./

