FROM python:3.11

RUN groupadd --gid 1000 nonroot && useradd --uid 1000 --gid 1000 -m nonroot

RUN pip install --no-cache --upgrade pip && pip install --no-cache pipenv

USER nonroot

WORKDIR /app

COPY ./Pipfile ./Pipfile.lock ./

RUN pipenv install --dev --deploy --ignore-pipfile --clear

COPY ./ ./

