services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/python:3
    volumes: [../:/app:cached]
    network_mode: service:mongo
    depends_on: [mongo]
    init: true
    command: sleep infinity

  mongo:
    image: mongo:5
    restart: unless-stopped
    volumes: [mongodb-data:/data/db]
    ports: [27017:27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

volumes:
  mongodb-data:
