services:
  biblion:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.10
    volumes: [../:/app:cached]
    depends_on: [mongo]
    init: true
    command: sleep infinity

  mongo:
    image: mongo:5
    restart: unless-stopped
    volumes: [mongodb-data:/data/db]
    ports: [27017:27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  mongodb-data:

networks:
  default: { name: "biblion-network" }
